name: Docker

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: to-do-list:production

    - name: Save Docker image
      run: |
        mkdir -p docker-image
        docker save to-do-list:production > docker-image/to-do-list.tar

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-image/to-do-list.tar"
        target: "/home/adavid"

    - name: Load and run Docker image on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load < /home/adavid/docker-image/to-do-list.tar
          docker run -d -p 3000:3000 to-do-list:production