name: To-Do List CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: to-do-list:production

    - name: Save Docker image
      run: |
        mkdir -p docker-image
        docker save to-do-list:production > docker-image/to-do-list.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-image/to-do-list.tar

  registry:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Docker image from artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-image
        path: docker-image

    - name: Log host and username
      run: |
        echo "Host: ${{ vars.HOST }}"
        echo "Username: ${{ vars.USERNAME }}"

    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-image/to-do-list.tar"
        target: "/home/root"

    - name: Copy Docker Compose file to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "/docker/deploy-compose.yml"
        target: "/home/root"

  deploy:
    needs: registry
    runs-on: ubuntu-latest
    steps:
    - name: Load and run Docker image on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load < /home/root/docker-image/to-do-list.tar
          docker compose -f /home/root/deploy-compose.yml up -d
          docker run --name to-do-list -d -p 3001:3000 to-do-list:production